import type { LlmProvider, LlmCompletionOptions } from '../types';

export class MockLlmProvider implements LlmProvider {
  async complete(options: LlmCompletionOptions): Promise<string> {
    const lastUserMessage = [...options.messages].reverse().find(m => m.role === 'user');
    const prompt = lastUserMessage?.content ?? '';

    // Simulate generating a diff patch for UI extension
    if (prompt.toLowerCase().includes('change') || prompt.toLowerCase().includes('update') || prompt.toLowerCase().includes('add')) {
      return `--- a/tenants/tenant-1/extensions/ui/index.tsx
+++ b/tenants/tenant-1/extensions/ui/index.tsx
@@ -1,5 +1,5 @@
 import React from 'react';
-export default function ExtensionPage() {
-  return <div>Extension Page</div>;
+export default function ExtensionPage() {
+  return <div>Updated by AI Agent: ${prompt.substring(0, 50)}</div>;
 }`;
    }

    return `I received your request: "${prompt}". No changes were generated by the mock provider.`;
  }

  async transcribeAudio(_audioBuffer: Buffer, _mimeType: string): Promise<string> {
    return 'Mock transcription: This is simulated voice input';
  }
}
